CREATE TABLE IF NOT EXISTS `Install_Data` (
 `Installed_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS `User_Data` (
 `User_Id` INT AUTO_INCREMENT NOT NULL,
 `User_Type` INT NOT NULL,
 `User_FullName` VARCHAR(120) NOT NULL,
 `User_Email` VARCHAR(255) NOT NULL,
 `Create_by` INT NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`User_Email`),
 PRIMARY KEY(`User_Id`)
);
CREATE TABLE IF NOT EXISTS `User_Token` (
 `User_Id` INT NOT NULL,
 `User_Token` CHAR(4) NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`User_Id`, `User_Token`),
 FOREIGN KEY(`User_Id`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `User_Sessions` (
 `User_Id` INT NOT NULL,
 `Session_Token` CHAR(32) NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`User_Id`, `Session_Token`),
 FOREIGN KEY(`User_Id`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);