CREATE TABLE IF NOT EXISTS `Carreras` (
  `Carrera_Id` INT(15) NOT NULL AUTO_INCREMENT,
  `Carrera_Name` VARCHAR(350) NOT NULL,
  `Create_by` INT NOT NULL,
  `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Carrera_Id`),
  UNIQUE KEY(`Carrera_Name`),
  FOREIGN KEY(`Create_by`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `Peds` (
  `Ped_Id` INT(15) NOT NULL AUTO_INCREMENT,
  `Ped_Name` VARCHAR(350) NOT NULL,
  `Create_by` INT NOT NULL,
  `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Ped_Id`),
  UNIQUE KEY(`Ped_Name`),
  FOREIGN KEY(`Create_by`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `Turnos` (
  `Turno_Id` INT(15) NOT NULL AUTO_INCREMENT,
  `Turno_Name` VARCHAR(350) NOT NULL,
  `Create_by` INT NOT NULL,
  `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Turno_Id`),
  UNIQUE KEY(`Turno_Name`),
  FOREIGN KEY(`Create_by`) REFERENCES `User_Data`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);